# ------
[rust]
name = "Rust"
id = "rust"

[[rust.groups]]
id = "rust-official"
name = "official rust repositories"
repos = []
orgs = ["rust-lang"]
flags = { "*" = ["good first issue"], "rust-lang" = ["E-easy"] }

[[rust.groups]]
id = "notable-web"
name = "notable web/networking rust repositories"
repos = [
    "seanmonstar/reqwest",
    "serenity-rs/serenity",
    "denoland/deno",
    "servo/servo",
    "tauri-apps/tauri",
    "actix/actix-web",
    "hyperium/hyper",
    "yewstack/yew",
    "meilisearch/MeiliSearch",
    "valeriansaliou/sonic",
    "swc-project/swc",
    "wasmerio/wasmer",
    "diesel-rs/diesel",
]
orgs = []
[rust.groups.flags]
"*" = ["good first issue"]
"servo/servo" = ["E-easy"]
"swc-project/swc" = ["E-easy"]
"actix/actix-web" = ["good-first-issue"]
"wasmerio/wasmer" = ["🥇 good first issue"]

[[rust.groups]]
id = "notable-general"
name = "notable general rust repositories"
repos = [
    "hecrj/iced",
    "tokio-rs/tokio",
    "serde-rs/serde",
    "rust-random/rand",
    "bitflags/bitflags",
    "async-rs/async-std",
    "smol-rs/smol",
    "sharkdp/fd",
    "starship/starship",
    "xi-editor/xi-editor",
    "alacritty/alacritty",
    "bevyengine/bevy",
    "sharkdp/bat",
    "nushell/nushell",
    "amethyst/amethyst",
]
orgs = []
[rust.groups.flags]
"*" = ["good first issue"]
"tokio-rs/tokio" = ["E-easy"]
"alacritty/alacritty" = ["D - easy"]
"starship/starship" = ["🌱 good first issue"]
"xi-editor/xi-editor" = ["easy"]
"amethyst/amethyst" = ["diff: easy"]

# ------

[python]
name = "Python"
id = "python"

[[python.groups]]
id = "python-official"
name = "official python repositories"
repos = []
orgs = ["python"]
flags = { "*" = ["good first issue", "good-first-issue"] }

[[python.groups]]
id = "notable-projects"
name = "notable python repositories"
repos = [
    "tensorflow/tensorflow",
    "pallets/flask",
    "keras-team/keras",
    "httpie/httpie",
    "pytorch/pytorch",
    "ansible/ansible",
    "scikit-learn/scikit-learn",
    "scrapy/scrapy",
    "3b1b/manim",
    "tiangolo/fastapi",
    "getsentry/sentry",
    "pandas-dev/pandas",
]
orgs = []
[python.groups.flags]
"*" = ["good first issue"]
"keras-team/keras" = ["Good first issue"]
"ansible/ansible" = ["easyfix"]
"getsentry/sentry" = ["Easy Task"]

# -----

[c]
name = "C"
id = "c"

[[c.groups]]
id = "notable-projects"
name = "notable c projects"
orgs = []
repos = [
    "Genymobile/scrcpy",
    "neovim/neovim",
    "obsproject/obs-studio",
    "microsoft/vcpkg",
    "CoatiSoftware/Sourcetrail",
    "glfw/glfw",
    "borgbackup/borg",
    "raysan5/raylib",
    "qmk/qmk_firmware",
    "lvgl/lvgl",
    "tree-sitter/tree-sitter",
    "emscripten-core/emscripten",
    "netdata/netdata"
]

[c.groups.flags]
"*" = ["good first issue"]
"obsproject/obs-studio" = ["Good first issue"]
"microsoft/vcpkg" = ["info:good-first-issue"]
"tree-sitter/tree-sitter" = ["good-starting-pr"]
"emscripten-core/emscripten" = ["good first bug"]

[hacktoberfest]
name = "Hacktoberfest"
id = "hacktoberfest"

[[hacktoberfest.groups]]
id = "notable-projects"
name = "notable hacktoberfest projects"
orgs = []
repos = [
    "ohmyzsh/ohmyzsh",
    "axios/axios",
    "mui/material-ui",
    "storybookjs/storybook",
    "huggingface/transformers",
    "gohugoio/hugo",
    "chartjs/Chart.js",
    "ansible/ansible",
    "tauri-apps/tauri",
    "grafana/grafana",
    "nestjs/nest",
    "mermaid-js/mermaid",
    "strapi/strapi",
    "caddyserver/caddy",
    "meteor/meteor",
    "scrapy/scrapy",
    "hoppscotch/hoppscotch",
    "JuliaLang/julia",
    "x64dbg/x64dbg",
    "facebook/docusaurus",
    "sharkdp/bat",
    "sherlock-project/sherlock"
]

[hacktoberfest.groups.flags]
"*" = ["good first issue"]
"ohmyzsh/ohmyzsh" = ["Good first issue"]
"axios/axios" = ["beginner"]
"huggingface/transformers" = ["Good First Issue"]
"gohugoio/hugo" = ["GoodFirstIssue"]
"chartjs/Chart.js" = ["type: documentation"]
"ansible/ansible" = ["easyfix"]
"nestjs/nest" = ["good first issue 👍"]
"mermaid-js/mermaid" = ["Good first issue!"]
