[rust]
name = "Rust"
id = "rust"

[[rust.groups]]
id = "rust-official"
name = "Official Rust Repositories"
repos = []
orgs = ["rust-lang"]
flags = { "*" = ["good first issue"], "rust-lang" = ["E-easy"] }

[[rust.groups]]
id = "notable-projects"
name = "Notable Rust repositories"
repos = [
    "hecrj/iced",
    "seanmonstar/reqwest",
    "tokio-rs/tokio",
    "serde-rs/serde",
    "rust-random/rand",
    "bitflags/bitflags",
    "serenity-rs/serenity",
    "async-rs/async-std",
    "smol-rs/smol",
    "denoland/deno",
    "alacritty/alacritty",
    "servo/servo",
    "tauri-apps/tauri",
    "actix/actix-web",
    "bevyengine/bevy",
    "hyperium/hyper",
]
orgs = []
[rust.groups.flags]
"*" = ["good first issue"]
"servo/servo" = ["E-easy"]
"tokio-rs/tokio" = ["E-easy"]
"alacritty/alacritty" = ["D - easy"]
"actix/actix-web" = ["good-first-issue"]
